spring.datasource.url=jdbc:postgresql://localhost:5432/edutrack
spring.datasource.username=postgres
spring.datasource.password=srInIvas@11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
